// <auto-generated />
using System;
using AcmeCourses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeCourses.Migrations
{
    [DbContext(typeof(Program.ApplicationContext))]
    [Migration("20251204123744_Initial first")]
    partial class Initialfirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Finnish_Swedish_CI_AS")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcmeCourses.Program+Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Programmering C#.NET",
                            Description = "Grundkurs C#.",
                            EducationId = 1,
                            EndDate = new DateOnly(2025, 10, 15),
                            StartDate = new DateOnly(2025, 8, 25)
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "SQL",
                            Description = "Databas och Databasdesign",
                            EducationId = 1,
                            EndDate = new DateOnly(2025, 10, 15),
                            StartDate = new DateOnly(2025, 10, 20)
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "UX",
                            Description = "Grafisk Design",
                            EducationId = 2,
                            EndDate = new DateOnly(2026, 10, 15),
                            StartDate = new DateOnly(2026, 8, 20)
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "AI/ChatGPT",
                            Description = "AI för programmerare",
                            EducationId = 2,
                            EndDate = new DateOnly(2026, 12, 11),
                            StartDate = new DateOnly(2026, 10, 22)
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "Analys och Rapport",
                            Description = "Analysera marknadsdata",
                            EducationId = 3,
                            EndDate = new DateOnly(2026, 12, 13),
                            StartDate = new DateOnly(2026, 10, 20)
                        },
                        new
                        {
                            Id = 6,
                            CourseName = "LIA",
                            Description = "Praktik",
                            EducationId = 3,
                            EndDate = new DateOnly(2027, 1, 11),
                            StartDate = new DateOnly(2026, 12, 15)
                        });
                });

            modelBuilder.Entity("AcmeCourses.Program+Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "En kombination utav teknik och programmering.",
                            Name = "Backendutvecklare"
                        },
                        new
                        {
                            Id = 2,
                            Description = "En kombination utav användarvänliga och visuella webbplatser.",
                            Name = "Frontendutvecklare"
                        },
                        new
                        {
                            Id = 3,
                            Description = "För framtidens dynamiska kommunikationslandskap.",
                            Name = "Digital kommunikatör"
                        });
                });

            modelBuilder.Entity("AcmeCourses.Program+Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationId = 1,
                            FirstName = "Fideli",
                            LastName = "Lundgren"
                        },
                        new
                        {
                            Id = 2,
                            EducationId = 2,
                            FirstName = "Niklas",
                            LastName = "Kääpä"
                        },
                        new
                        {
                            Id = 3,
                            EducationId = 3,
                            FirstName = "Joakim",
                            LastName = "Christiansson"
                        },
                        new
                        {
                            Id = 4,
                            EducationId = 2,
                            FirstName = "Ruhollah",
                            LastName = "Karim"
                        });
                });

            modelBuilder.Entity("AcmeCourses.Program+Course", b =>
                {
                    b.HasOne("AcmeCourses.Program+Education", null)
                        .WithMany("Courses")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcmeCourses.Program+Student", b =>
                {
                    b.HasOne("AcmeCourses.Program+Education", null)
                        .WithMany("Students")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcmeCourses.Program+Education", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
